library("ggplot2")
library("dplyr")
library("readxl")
library("dplyr")
library("tidyr")
library("readr")
library("XML")
library("xml2")
library("tidyverse")
library("stringdist")
library("hrbrthemes")
library("viridis")
library("plotrix")
library("stringr")
library("RColorBrewer")
library("rcompanion")

hansson_data_fragment <- read_excel("hansson.xlsx", sheet = 3)
hansson_data_fragment <- hansson_data_fragment %>% rename("Fragment Sequence" = "Sequence")
hansson_data_fragment <- hansson_data_fragment %>% rename("Fragment Sequence Length" = "Sequence Length")
hansson_data_fragment <- hansson_data_fragment %>% mutate("Positions in Master Proteins" = gsub("\\]; \\[", "], [", hansson_data_fragment$"Positions in Master Proteins"))
hansson_data_fragment <- hansson_data_fragment %>% separate_rows("Positions in Master Proteins", sep = "; ")
hansson_data_fragment <- hansson_data_fragment %>% separate("Positions in Master Proteins", into = c("Uniprot", "Location"), sep = "\\ ")
hansson_data_fragment <- hansson_data_fragment %>% filter("Location" != "" & !is.na("Location"))
hansson_data_fragment$"Uniprot" <- sub("\\-.*", "", hansson_data_fragment$"Uniprot")
hansson_data_fragment <- hansson_data_fragment %>% distinct(hansson_data_fragment$"Fragment Sequence", hansson_data_fragment$"Uniprot", .keep_all = TRUE)

uniprot_data <- read_tsv("uniprot_data.tsv")
colnames(uniprot_data) <- c("Uniprot", "Full Length", "Full Sequence", "Gene")
uniprot_data$"Gene" <- sub("\\ . *", "", uniprot_data$"Gene")

antigen <- read.csv("antigen.csv", sep=";")
antigen <- antigen %>% separate_rows("Uniprot", sep = ";")
antigen <- antigen %>% rename("Antigen Sequence" = "PrEST.seq..aa.")
antigen <- antigen %>% select("Antigen Sequence", "Uniprot", "Single.cell.type.Enriched.Enhanced.Tissue")

hpa <- read_tsv("proteinatlas.tsv")
hpa <- hpa %>% select("Gene", "Uniprot", "Protein class")

complete_hansson <- inner_join(uniprot_data, hansson_data_fragment, by = "Uniprot")
complete_hansson <- complete_hansson %>% select(-"Gene")
complete_hansson <- inner_join(hpa,complete_hansson, by = "Uniprot")

complete_hansson <- complete_hansson %>% select("Gene", "Uniprot", "Full Length", "Full Sequence", "Fragment Sequence", "Fragment Sequence Length", "Location", "Protein class")
